# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_address', models.TextField(blank=True, max_length=500)),
                ('nonce', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('email', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
