# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180606_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_address',
            field=models.TextField(blank=True, max_length=500, unique=True),
        ),
    ]
