# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 21:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180613_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_notifications',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='authentication.User'),
        ),
    ]
