 FROM python:3
 ENV PYTHONUNBUFFERED 1
 ARG auto_build="true"
 ENV auto_build=$auto_build
 RUN mkdir /code
 WORKDIR /code
 ADD requirements.txt /code/
 RUN pip install -r requirements.txt
 ADD . /code/
 EXPOSE 83
 CMD if [ "${auto_build}" = "true" ]; then python3 manage.py runserver 0.0.0.0:83 ; fi
 