# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BountiesTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bounties_issued', models.PositiveIntegerField()),
                ('fulfillments_submitted', models.PositiveIntegerField()),
                ('fulfillments_accepted', models.PositiveIntegerField()),
                ('fulfillments_pending_acceptance', models.PositiveIntegerField()),
                ('fulfillment_acceptance_rate', models.FloatField()),
                ('bounty_fulfilled_rate', models.FloatField()),
                ('avg_fulfiller_acceptance_rate', models.FloatField()),
                ('avg_fulfillment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fulfillment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bounty_draft', models.PositiveIntegerField()),
                ('bounty_active', models.PositiveIntegerField()),
                ('bounty_completed', models.PositiveIntegerField()),
                ('bounty_expired', models.PositiveIntegerField()),
                ('bounty_dead', models.PositiveIntegerField()),
            ],
        ),
    ]
