# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 18:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128)),
                ('transaction_hash', models.CharField(max_length=128)),
                ('bounty_id', models.IntegerField()),
                ('fulfillment_id', models.IntegerField()),
                ('transaction_from', models.CharField(max_length=128)),
                ('event_timestamp', models.IntegerField()),
                ('contract_method_inputs', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('transaction_hash', 'event_name')]),
        ),
    ]
