# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20180502_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountiestimeline',
            name='avg_fulfillment_amount',
            field=models.FloatField(),
        ),
    ]
