# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_bountiestimeline_is_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountiestimeline',
            name='schema',
        ),
        migrations.AddField(
            model_name='bountiestimeline',
            name='platform',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
