# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_bountiestimeline_is_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(max_length=128)),
                ('token_contract', models.CharField(max_length=128)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('usd_price', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='bountiestimeline',
            old_name='schema',
            new_name='platform',
        ),
    ]
