# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20180503_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountiestimeline',
            name='bounties_issued_cum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bountiestimeline',
            name='fulfillments_accepted_cum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bountiestimeline',
            name='fulfillments_submitted_cum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='avg_fulfiller_acceptance_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='avg_fulfillment_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='bounties_issued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='bounty_active',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='bounty_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='bounty_dead',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='bounty_draft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='bounty_expired',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='bounty_fulfilled_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='fulfillment_acceptance_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='fulfillments_accepted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='fulfillments_pending_acceptance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='fulfillments_submitted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bountiestimeline',
            name='total_fulfillment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=64),
        ),
    ]
