# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20180503_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountiestimeline',
            name='schema',
            field=models.CharField(default='all', max_length=64),
        ),
    ]
