# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_bountiestimeline_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountiestimeline',
            name='schema',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
