# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 16:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bounty_id', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('data', models.CharField(max_length=128)),
                ('issuer', models.CharField(max_length=128)),
                ('arbiter', models.CharField(max_length=128, null=True)),
                ('fulfillmentAmount', models.DecimalField(decimal_places=18, max_digits=64)),
                ('paysTokens', models.BooleanField()),
                ('bountystage', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Dead', 'Dead')], default='Draft', max_length=128)),
                ('old_balance', models.DecimalField(decimal_places=18, max_digits=64, null=True)),
                ('balance', models.DecimalField(decimal_places=18, max_digits=64)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('data_issuer', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('funders', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('categories', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('bounty_created', models.DateTimeField(null=True)),
                ('tokenSymbol', models.CharField(blank=True, max_length=64)),
                ('tokenAddress', models.CharField(blank=True, max_length=128)),
                ('sourceFileName', models.CharField(blank=True, max_length=256)),
                ('sourceFileHash', models.CharField(blank=True, max_length=256)),
                ('sourceDirectoryHash', models.CharField(blank=True, max_length=256)),
                ('webReferenceUrl', models.CharField(blank=True, max_length=256)),
                ('platform', models.CharField(blank=True, max_length=128)),
                ('schemaVersion', models.CharField(blank=True, max_length=64)),
                ('schemaName', models.CharField(max_length=128, null=True)),
                ('data_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fulfillment_id', models.IntegerField()),
                ('data', models.CharField(max_length=128)),
                ('accepted', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('sourceFileName', models.CharField(blank=True, max_length=256)),
                ('sourceFileHash', models.CharField(blank=True, max_length=256)),
                ('sourceDirectoryHash', models.CharField(blank=True, max_length=256)),
                ('fulfiller', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('platform', models.CharField(blank=True, max_length=128)),
                ('schemaVersion', models.CharField(blank=True, max_length=64)),
                ('schemaName', models.CharField(blank=True, max_length=128)),
                ('data_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Bounty')),
            ],
        ),
    ]
