# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 21:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bounty_id', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('data', models.CharField(max_length=128)),
                ('issuer', models.CharField(max_length=128)),
                ('arbiter', models.CharField(max_length=128, null=True)),
                ('fulfillmentAmount', models.DecimalField(decimal_places=18, max_digits=64)),
                ('paysTokens', models.BooleanField()),
                ('bountyStage', models.IntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Dead'), (3, 'Completed'), (4, 'Expired')], default=0)),
                ('old_balance', models.DecimalField(decimal_places=18, max_digits=64, null=True)),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=64, null=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('funders', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('bounty_created', models.DateTimeField(null=True)),
                ('tokenSymbol', models.CharField(blank=True, max_length=64)),
                ('tokenContract', models.CharField(blank=True, max_length=128)),
                ('tokenAddress', models.CharField(blank=True, max_length=128)),
                ('sourceFileName', models.CharField(blank=True, max_length=256)),
                ('sourceFileHash', models.CharField(blank=True, max_length=256)),
                ('sourceDirectoryHash', models.CharField(blank=True, max_length=256)),
                ('webReferenceUrl', models.CharField(blank=True, max_length=256)),
                ('platform', models.CharField(blank=True, max_length=128)),
                ('schemaVersion', models.CharField(blank=True, max_length=64)),
                ('schemaName', models.CharField(max_length=128, null=True)),
                ('data_categories', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('data_issuer', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('data_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('normalized_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fulfillment_id', models.IntegerField()),
                ('fulfillment_created', models.DateTimeField(null=True)),
                ('data', models.CharField(max_length=128)),
                ('accepted', models.BooleanField()),
                ('fulfiller', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sourceFileName', models.CharField(blank=True, max_length=256)),
                ('sourceFileHash', models.CharField(blank=True, max_length=256)),
                ('sourceDirectoryHash', models.CharField(blank=True, max_length=256)),
                ('platform', models.CharField(blank=True, max_length=128)),
                ('schemaVersion', models.CharField(blank=True, max_length=64)),
                ('schemaName', models.CharField(blank=True, max_length=128)),
                ('data_fulfiller', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('data_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Bounty')),
            ],
        ),
        migrations.AddField(
            model_name='bounty',
            name='categories',
            field=models.ManyToManyField(null=True, to='std_bounties.Category'),
        ),
    ]
