# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 02:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(max_length=128)),
                ('total_count', models.IntegerField()),
            ],
            options={
                'db_table': 'category_ranks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bounty_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField()),
                ('data', models.CharField(max_length=128)),
                ('issuer', models.CharField(max_length=128)),
                ('arbiter', models.CharField(max_length=128, null=True)),
                ('fulfillmentAmount', models.DecimalField(decimal_places=0, max_digits=64)),
                ('paysTokens', models.BooleanField()),
                ('bountyStage', models.IntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Dead'), (3, 'Completed'), (4, 'Expired')], default=0)),
                ('old_balance', models.DecimalField(decimal_places=0, max_digits=64, null=True)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=70, null=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('bounty_created', models.DateTimeField(null=True)),
                ('tokenSymbol', models.CharField(default='ETH', max_length=128)),
                ('tokenDecimals', models.IntegerField(default=18)),
                ('tokenContract', models.CharField(default='0x0000000000000000000000000000000000000000', max_length=128)),
                ('usd_price', models.FloatField(default=0)),
                ('issuer_name', models.CharField(blank=True, max_length=128)),
                ('issuer_email', models.CharField(blank=True, max_length=128)),
                ('issuer_githubUsername', models.CharField(blank=True, max_length=128)),
                ('issuer_address', models.CharField(blank=True, max_length=128)),
                ('sourceFileName', models.CharField(blank=True, max_length=256)),
                ('sourceFileHash', models.CharField(blank=True, max_length=256)),
                ('sourceDirectoryHash', models.CharField(blank=True, max_length=256)),
                ('webReferenceUrl', models.CharField(blank=True, max_length=256)),
                ('platform', models.CharField(blank=True, max_length=128)),
                ('schemaVersion', models.CharField(blank=True, max_length=64)),
                ('schemaName', models.CharField(max_length=128, null=True)),
                ('data_categories', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('data_issuer', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('data_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('normalized_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fulfillment_created', models.DateTimeField(null=True)),
                ('data', models.CharField(max_length=128)),
                ('accepted', models.BooleanField()),
                ('fulfiller', models.CharField(max_length=128)),
                ('fulfiller_name', models.CharField(blank=True, max_length=128)),
                ('fulfiller_email', models.CharField(blank=True, max_length=128)),
                ('fulfiller_githubUsername', models.CharField(blank=True, max_length=128)),
                ('fulfiller_address', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sourceFileName', models.CharField(blank=True, max_length=256)),
                ('sourceFileHash', models.CharField(blank=True, max_length=256)),
                ('sourceDirectoryHash', models.CharField(blank=True, max_length=256)),
                ('platform', models.CharField(blank=True, max_length=128)),
                ('schemaVersion', models.CharField(blank=True, max_length=64)),
                ('schemaName', models.CharField(blank=True, max_length=128)),
                ('data_fulfiller', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('data_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='std_bounties.Bounty')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=128)),
                ('price_usd', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bounty',
            name='categories',
            field=models.ManyToManyField(null=True, to='std_bounties.Category'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Token'),
        ),
    ]
