# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0003_bountystate_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='webReferenceUrl',
            new_name='webReferenceURL',
        ),
        migrations.AddField(
            model_name='bounty',
            name='calculated_balance',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=70, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='calculated_fulfillmentAmount',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=70, null=True),
        ),
    ]
