# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('std_bounties', '0004_auto_20180427_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
