# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0005_auto_20180503_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')], null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='revisions',
            field=models.IntegerField(null=True),
        ),
    ]
