# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 20:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180614_2013'),
        ('std_bounties', '0005_auto_20180503_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
        ),
        migrations.CreateModel(
            name='DraftBounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField()),
                ('arbiter', models.CharField(max_length=128, null=True)),
                ('fulfillmentAmount', models.DecimalField(decimal_places=0, max_digits=64)),
                ('calculated_fulfillmentAmount', models.DecimalField(decimal_places=30, default=0, max_digits=70, null=True)),
                ('paysTokens', models.BooleanField()),
                ('experienceLevel', models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')], null=True)),
                ('revisions', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('tokenSymbol', models.CharField(default='ETH', max_length=128)),
                ('tokenDecimals', models.IntegerField(default=18)),
                ('tokenContract', models.CharField(default='0x0000000000000000000000000000000000000000', max_length=128)),
                ('usd_price', models.FloatField(default=0)),
                ('issuer_name', models.CharField(blank=True, max_length=128)),
                ('issuer_email', models.CharField(blank=True, max_length=128)),
                ('issuer_githubUsername', models.CharField(blank=True, max_length=128)),
                ('issuer_address', models.CharField(blank=True, max_length=128)),
                ('sourceFileName', models.CharField(blank=True, max_length=256)),
                ('sourceFileHash', models.CharField(blank=True, max_length=256)),
                ('sourceDirectoryHash', models.CharField(blank=True, max_length=256)),
                ('webReferenceURL', models.CharField(blank=True, max_length=256)),
                ('platform', models.CharField(blank=True, max_length=128)),
                ('schemaVersion', models.CharField(blank=True, max_length=64)),
                ('schemaName', models.CharField(max_length=128, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('data', models.CharField(blank=True, max_length=128, null=True)),
                ('issuer', models.CharField(blank=True, max_length=128, null=True)),
                ('on_chain', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(null=True, to='std_bounties.Category')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Token')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('review', models.TextField()),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewees', to='authentication.User')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='authentication.User')),
            ],
        ),
        migrations.AddField(
            model_name='bounty',
            name='experienceLevel',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')], null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='revisions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='uid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='bounty', to='std_bounties.Comment'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='fulfiller_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_review', to='std_bounties.Review'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='issuer_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_review', to='std_bounties.Review'),
        ),
    ]
