# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180606_1425'),
        ('std_bounties', '0006_auto_20180606_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
        ),
        migrations.AddField(
            model_name='bounty',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='bounty', to='std_bounties.Comment'),
        ),
    ]
