# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0007_auto_20180726_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='categories',
            field=models.ManyToManyField(to='std_bounties.Category'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='comments',
            field=models.ManyToManyField(related_name='bounty', to='std_bounties.Comment'),
        ),
        migrations.AlterField(
            model_name='draftbounty',
            name='categories',
            field=models.ManyToManyField(to='std_bounties.Category'),
        ),
    ]
