# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 19:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180606_1425'),
        ('std_bounties', '0007_auto_20180606_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('review', models.TextField()),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewees', to='authentication.User')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='authentication.User')),
            ],
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='fulfiller_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_review', to='std_bounties.Review'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='issuer_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_review', to='std_bounties.Review'),
        ),
    ]
