# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0008_auto_20180731_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
