# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-11 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0010_auto_20180803_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
