# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0012_review_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='platform',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
