# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0013_category_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='platform',
        ),
    ]
