# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0015_auto_20180905_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='private_fulfillments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='draftbounty',
            name='private_fulfillments',
            field=models.BooleanField(default=True),
        ),
    ]
