# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-23 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0015_auto_20180906_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='image_preview',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
