# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_dismissed_signup_prompt'),
        ('std_bounties', '0016_bounty_image_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('state', models.CharField(choices=[('A', 'accepted'), ('R', 'rejected'), ('P', 'pending')], default='P', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='bounty',
            name='fulfillers_need_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='fulfillers_need_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fulfillerapplication',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Bounty'),
        ),
    ]
