# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0016_bounty_image_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='categories',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='draftbounty',
            old_name='categories',
            new_name='tags',
        ),
    ]
