# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0017_auto_20190131_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='contract_version',
            field=models.IntegerField(default=1),
        ),
    ]
