# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0017_auto_20181004_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(max_length=128)),
                ('total_count', models.IntegerField()),
                ('platform', models.CharField(default='main', max_length=128)),
            ],
            options={
                'db_table': 'tag_ranks',
                'managed': False,
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
    ]
