# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0018_auto_20181004_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='data_categories',
            new_name='data_tags',
        ),
    ]
