# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-31 18:07
from __future__ import unicode_literals

from django.db import migrations


def to_token_type(apps, schema_editor):
    Bounty = apps.get_model('std_bounties', 'Bounty')
    Draft = apps.get_model('std_bounties', 'DraftBounty')

    print('beginning')

    for bounty in Bounty.objects.all():
        if bounty.paysTokens:
            bounty.token_version = 20
        else:
            bounty.token_version = 0

        bounty.save()

    for draft in Draft.objects.all():
        if draft.paysTokens:
            draft.token_version = 20
        else:
            draft.token_version = 0

        draft.save()


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0018_auto_20190331_1807'),
    ]

    operations = [
        migrations.RunPython(to_token_type)
    ]
