# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 05:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0018_bounty_contract_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='contributions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='platform',
            field=models.CharField(blank=True, default='bounties-network', max_length=128),
        ),
    ]
