# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-22 17:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0018_auto_20190321_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contract_event_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
