# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-31 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='paysTokens',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='paysTokens',
        ),
    ]
