# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-08 20:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0019_auto_20190307_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='fulfillers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None),
        ),
    ]
