# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-23 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0019_event_contract_event_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='tokenLockPrice',
            new_name='token_lock_price',
        ),
    ]
