# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-01 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0020_auto_20190331_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='schemaName',
            new_name='schema_name',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='schemaVersion',
            new_name='schema_version',
        ),
        migrations.RenameField(
            model_name='draftbounty',
            old_name='schemaName',
            new_name='schema_name',
        ),
        migrations.RenameField(
            model_name='draftbounty',
            old_name='schemaVersion',
            new_name='schema_version',
        ),
    ]
