# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-11 16:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0020_fulfillment_fulfillers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='approvers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='issuers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='tokenVersion',
            field=models.IntegerField(null=True),
        ),
    ]
