# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 17:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20190223_1548'),
        ('std_bounties', '0021_auto_20190311_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='sourceDirectoryHash',
            new_name='attached_data_hash',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='sourceFileName',
            new_name='attached_filename',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='webReferenceURL',
            new_name='attached_url',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='bountyStage',
            new_name='bounty_stage',
        ),
        migrations.RenameField(
            model_name='draftbounty',
            old_name='sourceDirectoryHash',
            new_name='attached_data_hash',
        ),
        migrations.RenameField(
            model_name='draftbounty',
            old_name='sourceFileName',
            new_name='attached_filename',
        ),
        migrations.RenameField(
            model_name='draftbounty',
            old_name='webReferenceURL',
            new_name='attached_url',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='arbiter',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='contract_version',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='contributions',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='issuer_address',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='issuer_email',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='issuer_githubUsername',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='issuer_name',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='sourceFileHash',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='tokenContract',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='tokenDecimals',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='tokenSymbol',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='tokenVersion',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='arbiter',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='issuer_address',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='issuer_email',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='issuer_githubUsername',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='issuer_name',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='sourceFileHash',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='tokenContract',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='tokenDecimals',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='tokenSymbol',
        ),
        migrations.AddField(
            model_name='bounty',
            name='contract_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='approvers',
            field=models.ManyToManyField(related_name='std_bounties_draftbounty_relateda', to='user.User'),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='issuers',
            field=models.ManyToManyField(related_name='std_bounties_draftbounty_related', to='user.User'),
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='approvers',
        ),
        migrations.AddField(
            model_name='bounty',
            name='approvers',
            field=models.ManyToManyField(related_name='std_bounties_bounty_relateda', to='user.User'),
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='issuers',
        ),
        migrations.AddField(
            model_name='bounty',
            name='issuers',
            field=models.ManyToManyField(related_name='std_bounties_bounty_related', to='user.User'),
        ),
    ]
