# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0021_auto_20190401_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='attached_data_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='attached_filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='attached_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='draftbounty',
            name='attached_data_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='draftbounty',
            name='attached_filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='draftbounty',
            name='attached_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
