# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0022_auto_20190312_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='calculated_fulfillmentAmount',
            new_name='calculated_fulfillment_amount',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='experienceLevel',
            new_name='experience_level',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='fulfillmentAmount',
            new_name='fulfillment_amount',
        ),
        migrations.RenameField(
            model_name='draftbounty',
            old_name='calculated_fulfillmentAmount',
            new_name='calculated_fulfillment_amount',
        ),
        migrations.RenameField(
            model_name='draftbounty',
            old_name='experienceLevel',
            new_name='experience_level',
        ),
        migrations.RenameField(
            model_name='draftbounty',
            old_name='fulfillmentAmount',
            new_name='fulfillment_amount',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='paysTokens',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='paysTokens',
        ),
        migrations.AddField(
            model_name='bounty',
            name='token_contract',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=128),
        ),
        migrations.AddField(
            model_name='bounty',
            name='token_version',
            field=models.IntegerField(choices=[(0, 'Ether'), (20, 'ERC-20'), (721, 'ERC-721')], null=True),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='token_contract',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=128),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='token_version',
            field=models.IntegerField(choices=[(0, 'Ether'), (20, 'ERC-20'), (721, 'ERC-721')], null=True),
        ),
    ]
