# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0022_auto_20190401_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftbounty',
            name='approvers',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='issuers',
        ),
    ]
