# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0023_auto_20190502_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='issuer_address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bounty',
            name='issuer_email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bounty',
            name='issuer_githubUsername',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bounty',
            name='issuer_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='issuer_address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='issuer_email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='issuer_githubUsername',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='issuer_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
