# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0024_auto_20190313_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='user',
        ),
    ]
