# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 15:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20190223_1548'),
        ('std_bounties', '0024_auto_20190313_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded', models.BooleanField(default=False)),
                ('contribution_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=64)),
                ('calculated_amount', models.DecimalField(decimal_places=30, default=0, max_digits=70, null=True)),
                ('usd_amount', models.FloatField(default=0)),
                ('platform', models.CharField(blank=True, default='bounties-network', max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('raw_event_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bountystate',
            old_name='bountyStage',
            new_name='bounty_stage',
        ),
        migrations.AddField(
            model_name='bounty',
            name='contract_version',
            field=models.IntegerField(choices=[(1, 'v1'), (2, 'v2')], default=1),
        ),
        migrations.AddField(
            model_name='bounty',
            name='raw_event_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='raw_ipfs_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='token_decimals',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='bounty',
            name='token_symbol',
            field=models.CharField(default='ETH', max_length=128),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='token_decimals',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='token_symbol',
            field=models.CharField(default='ETH', max_length=128),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='contract_version',
            field=models.IntegerField(choices=[(1, 'v1'), (2, 'v2')], default=1),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='fulfillment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='draftbounty',
            name='fulfillment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=64),
        ),
        migrations.AddField(
            model_name='contribution',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Bounty'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
