# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0025_auto_20190509_1751'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['bounty_id', 'contract_version'], name='std_bountie_bounty__f4a070_idx'),
        ),
    ]
