# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0025_auto_20190509_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
