# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0025_auto_20190313_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='token_decimals',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='bounty',
            name='token_symbol',
            field=models.CharField(default='ETH', max_length=128),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='token_decimals',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='token_symbol',
            field=models.CharField(default='ETH', max_length=128),
        ),
    ]
