# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0026_auto_20190516_0510'),
        ('std_bounties', '0026_auto_20190516_1722'),
    ]

    operations = [
    ]
