# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0026_auto_20190313_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bountystate',
            old_name='bountyStage',
            new_name='bounty_stage',
        ),
    ]
