# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0028_auto_20190314_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='fulfillment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='draftbounty',
            name='fulfillment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=64),
        ),
    ]
