# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0028_auto_20190331_1807'),
        ('std_bounties', '0027_merge_20190516_1743'),
    ]

    operations = [
    ]
