# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0029_merge_20190530_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='comments',
            field=models.ManyToManyField(related_name='fulfillment', to='std_bounties.Comment'),
        ),
    ]
