# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0030_bounty_contract_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
