# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0030_fulfillment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='contract_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='contract_version',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
