# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0031_auto_20190909_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftbounty',
            name='approvers',
        ),
        migrations.RemoveField(
            model_name='draftbounty',
            name='issuers',
        ),
    ]
