# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0033_auto_20191111_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillerapplication',
            name='issuer_reply',
            field=models.TextField(default=''),
        ),
    ]
