# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0034_fulfillerapplication_issuer_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(blank=True, max_length=64)),
                ('contract_version', models.CharField(blank=True, max_length=64)),
                ('contract_address', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
