# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20190909_2029'),
        ('std_bounties', '0036_contract_abi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=128)),
                ('bounty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Bounty')),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Comment')),
                ('fulfillment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Fulfillment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(blank=True, max_length=128)),
                ('community_name', models.CharField(blank=True, max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total_members', models.IntegerField()),
                ('small_profile_image_url', models.CharField(blank=True, max_length=256)),
                ('large_profile_image_url', models.CharField(blank=True, max_length=256)),
                ('public', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='bounty',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Community'),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Community'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Community'),
        ),
    ]
