# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0037_auto_20191127_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Community'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='network',
            field=models.CharField(default='mainNet', max_length=256),
        ),
        migrations.AddField(
            model_name='community',
            name='network',
            field=models.CharField(default='mainNet', max_length=256),
        ),
        migrations.AddField(
            model_name='contract',
            name='network',
            field=models.CharField(default='mainNet', max_length=256),
        ),
        migrations.AddField(
            model_name='draftbounty',
            name='network',
            field=models.CharField(default='mainNet', max_length=256),
        ),
        migrations.AddField(
            model_name='event',
            name='network',
            field=models.CharField(default='mainNet', max_length=256),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='network',
            field=models.CharField(default='mainNet', max_length=256),
        ),
    ]
