# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0038_auto_20191127_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='bounty_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='community',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='fulfillment_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
