# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20190909_2029'),
        ('std_bounties', '0039_auto_20191129_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=128)),
                ('bounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Bounty')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Comment')),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Community')),
                ('fulfillment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Fulfillment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
