# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0040_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='total_members',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
