# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0041_auto_20191202_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='comments',
            field=models.ManyToManyField(related_name='bounty_comments', to='std_bounties.Comment'),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='comments',
            field=models.ManyToManyField(related_name='fulfillment_comments', to='std_bounties.Comment'),
        ),
    ]
