# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0042_auto_20191202_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Community'),
        ),
    ]
