# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-03 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0043_comment_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
