# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0045_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillerapplication',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
