# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0046_auto_20191204_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='decimals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='normalized_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='symbol',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
