# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0047_auto_20191204_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='normalized_name',
        ),
    ]
