# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-05 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('std_bounties', '0048_remove_token_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Token'),
        ),
    ]
