# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      image: circleci/classic:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install codecov
          command: |
            pip install codecov==2.0.15

      - run:
          name: python linter
          command: |
            pyenv global 3.5.2
            pip3 install flake8==3.5.0
            flake8 --ignore=E501,F405,W191

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io

      - run:
          name: build docker image
          command: |
            docker build ./bounties_api --tag consensysbounties/std_bounties:$CIRCLE_SHA1
            
      - run:
          name: Create docker postgres volume
          command: |
            docker volume create --name psql_bounties

      - run:
          name: run django tests
          command: |
            docker-compose -f docker-compose-circleci-test.yml run bounties_api python manage.py test

      - run:
          name: codecov upload
          command: |
            bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: test-reports
          destination: test-reports

      # - run:
      #     name: log in to docker hub
      #     command: |
      #       docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      # - run:
      #     name: upload docker image
      #     command: |
      #       docker push consensysbounties/std_bounties:$CIRCLE_SHA1
