# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='is_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_name',
            field=models.IntegerField(choices=[(0, 'FulfillmentSubmitted'), (1, 'BountyActivated'), (2, 'FulfillmentAccepted'), (13, 'BountyExpired'), (4, 'BountyFulfilled'), (5, 'BountyIssued'), (6, 'BountyKilled'), (7, 'ContributionAdded'), (8, 'DeadlineExtended'), (9, 'BountyChanged'), (10, 'IssuerTransferred'), (11, 'TransferRecipient'), (12, 'PayoutIncreased'), (13, 'BountyExpired'), (14, 'BountyComment'), (15, 'BountyIssuedActivated'), (16, 'FulfillmentUpdated')]),
        ),
    ]