# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180529_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='email',
            new_name='email_sent',
        ),
        migrations.AddField(
            model_name='notification',
            name='uid',
            field=models.CharField(default='hi', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_name',
            field=models.IntegerField(choices=[(0, 'FulfillmentSubmitted'), (1, 'BountyActivated'), (2, 'FulfillmentAccepted'), (12, 'BountyExpired'), (4, 'BountyIssued'), (5, 'BountyKilled'), (6, 'ContributionAdded'), (7, 'DeadlineExtended'), (8, 'BountyChanged'), (9, 'IssuerTransferred'), (10, 'TransferRecipient'), (11, 'PayoutIncreased'), (12, 'BountyExpired'), (13, 'BountyComment'), (14, 'BountyIssuedActivated'), (15, 'FulfillmentUpdated')]),
        ),
    ]
