# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 20:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180614_2013'),
        ('notifications', '0002_auto_20180529_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tx_hash', models.CharField(max_length=256, unique=True)),
                ('failed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email',
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='uid',
            field=models.CharField(default='y', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_name',
            field=models.IntegerField(choices=[(0, 'FulfillmentSubmitted'), (1, 'FulfillmentSubmittedIssuer'), (2, 'BountyActivated'), (3, 'FulfillmentAccepted'), (4, 'FulfillmentAcceptedFulfiller'), (14, 'BountyExpired'), (6, 'BountyIssued'), (7, 'BountyKilled'), (8, 'ContributionAdded'), (9, 'DeadlineExtended'), (10, 'BountyChanged'), (11, 'IssuerTransferred'), (12, 'TransferRecipient'), (13, 'PayoutIncreased'), (14, 'BountyExpired'), (15, 'BountyComment'), (16, 'BountyIssuedActivated'), (17, 'FulfillmentUpdated'), (18, 'FulfillmentUpdatedIssuer'), (19, 'RatingIssued'), (20, 'RatingReceived')]),
        ),
    ]
