# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 11:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180606_1425'),
        ('notifications', '0003_auto_20180611_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tx_hash', models.CharField(max_length=256)),
                ('failed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
        ),
    ]
