# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180803_1229'),
        ('notifications', '0005_auto_20180731_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='originating_user', to='user.User'),
        ),
    ]
