# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20180804_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='platform',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
