# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20180818_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='platform',
        ),
    ]
