# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0024_user_dismissed_signup_prompt'),
        ('std_bounties', '0016_bounty_image_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('DCR', 'DRAFT_CREATED'), ('DUP', 'DRAFT_UPDATED'), ('BIS', 'BOUNTY_ISSUED'), ('BAC', 'BOUNTY_ACTIVATED'), ('BEX', 'BOUNTY_EXPIRED'), ('BKI', 'BOUNTY_KILLED'), ('BCO', 'BOUNTY_COMPLETED'), ('BCA', 'BOUNTY_CONTRIBUTION_ADDED'), ('BDE', 'BOUNTY_DEADLINE_EXTENDED'), ('BTR', 'BOUNTY_TRANSFERRED'), ('BPI', 'BOUNTY_PAYOUT_INCREASED'), ('BCC', 'BOUNTY_COMMENT_CREATED'), ('FSU', 'FULFILLMENT_SUBMITTED'), ('FAC', 'FULFILLMENT_ACCEPTED'), ('UPU', 'USER_PROFILE_UPDATED'), ('URI', 'USER_RATING_ISSUED'), ('UJG', 'USER_JOINED_GROUP'), ('ULG', 'USER_LEFT_GROUP')], max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounty', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Bounty')),
                ('draft', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.DraftBounty')),
                ('fulfillment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std_bounties.Fulfillment')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Target'),
        ),
    ]
