# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='verb',
            field=models.CharField(choices=[('DCR', 'DRAFT_CREATED'), ('DUP', 'DRAFT_UPDATED'), ('BIS', 'BOUNTY_ISSUED'), ('BAC', 'BOUNTY_ACTIVATED'), ('BEX', 'BOUNTY_EXPIRED'), ('BKI', 'BOUNTY_KILLED'), ('BCO', 'BOUNTY_COMPLETED'), ('BCA', 'BOUNTY_CONTRIBUTION_ADDED'), ('BDE', 'BOUNTY_DEADLINE_EXTENDED'), ('BTR', 'BOUNTY_TRANSFERRED'), ('BPI', 'BOUNTY_PAYOUT_INCREASED'), ('BCC', 'BOUNTY_COMMENT_CREATED'), ('FCR', 'FULFILLMENT_CREATED'), ('FAC', 'FULFILLMENT_ACCEPTED'), ('UPU', 'USER_PROFILE_UPDATED'), ('URI', 'USER_RATING_ISSUED'), ('UJG', 'USER_JOINED_GROUP'), ('ULG', 'USER_LEFT_GROUP')], max_length=3),
        ),
    ]
