FULFILLMENT_SUBMITTED = 0
BOUNTY_ACTIVATED = 1
FULFILLMENT_ACCEPTED = 2
BOUNTY_EXPIRED = 3
BOUNTY_ISSUED = 4
BOUNTY_KILLED = 5
CONTRIBUTION_ADDED = 6
DEADLINE_EXTENDED = 7
BOUNTY_CHANGED = 8
ISSUER_TRANSFERRED = 9
TRANSFER_RECIPIENT = 10
PAYOUT_INCREASED = 11
BOUNTY_EXPIRED = 12
BOUNTY_COMMENT = 13
BOUNTY_ISSUED_ACTIVATED = 14
FULFILLMENT_UPDATED = 15

NOTIFICATION_IDS = (
    (FULFILLMENT_SUBMITTED, 'FulfillmentSubmitted'),
    (BOUNTY_ACTIVATED, 'BountyActivated'),
    (FULFILLMENT_ACCEPTED, 'FulfillmentAccepted'),
    (BOUNTY_EXPIRED, 'BountyExpired'),
    (BOUNTY_ISSUED, 'BountyIssued'),
    (BOUNTY_KILLED, 'BountyKilled'),
    (CONTRIBUTION_ADDED, 'ContributionAdded'),
    (DEADLINE_EXTENDED, 'DeadlineExtended'),
    (BOUNTY_CHANGED, 'BountyChanged'),
    (ISSUER_TRANSFERRED, 'IssuerTransferred'),
    (TRANSFER_RECIPIENT, 'TransferRecipient'),
    (PAYOUT_INCREASED, 'PayoutIncreased'),
    (BOUNTY_EXPIRED, 'BountyExpired'),
    (BOUNTY_COMMENT, 'BountyComment'),
    (BOUNTY_ISSUED_ACTIVATED, 'BountyIssuedActivated'),
    (FULFILLMENT_UPDATED, 'FulfillmentUpdated'),
)
