FULFILLMENT_SUBMITTED = 0
BOUNTY_ACTIVATED = 1
FULFILLMENT_ACCEPTED = 2
BOUNTY_EXPIRED = 3
BOUNTY_FULFILLED = 4
BOUNTY_ISSUED = 5
BOUNTY_KILLED = 6
CONTRIBUTION_ADDED = 7
DEADLINE_EXTENDED = 8
BOUNTY_CHANGED = 9
ISSUER_TRANSFERRED = 10
TRANSFER_RECIPIENT = 11
PAYOUT_INCREASED = 12
BOUNTY_EXPIRED = 13
BOUNTY_COMMENT = 14
BOUNTY_ISSUED_ACTIVATED = 15

NOTIFICATION_IDS = (
    (FULFILLMENT_SUBMITTED, 'FulfillmentSubmitted'),
    (BOUNTY_ACTIVATED, 'BountyActivated'),
    (FULFILLMENT_ACCEPTED, 'FulfillmentAccepted'),
    (BOUNTY_EXPIRED, 'BountyExpired'),
    (BOUNTY_FULFILLED, 'BountyFulfilled'),
    (BOUNTY_ISSUED, 'BountyIssued'),
    (BOUNTY_KILLED, 'BountyKilled'),
    (CONTRIBUTION_ADDED, 'ContributionAdded'),
    (DEADLINE_EXTENDED, 'DeadlineExtended'),
    (BOUNTY_CHANGED, 'BountyChanged'),
    (ISSUER_TRANSFERRED, 'IssuerTransferred'),
    (TRANSFER_RECIPIENT, 'TransferRecipient'),
    (PAYOUT_INCREASED, 'PayoutIncreased'),
    (BOUNTY_EXPIRED, 'BountyExpired'),
    (BOUNTY_COMMENT, 'BountyComment'),
    (BOUNTY_ISSUED_ACTIVATED, 'BountyIssuedActivated'),
)
