FULFILLMENT_SUBMITTED = 0
BOUNTY_ACTIVATED = 1
FULFILLMENT_ACCEPTED = 2
BOUNTY_EXPIRED = 3

NOTIFICATION_IDS = (
    (FULFILLMENT_SUBMITTED, 'FulfillmentSubmitted'),
    (BOUNTY_ACTIVATED, 'BountyActivated'),
    (FULFILLMENT_ACCEPTED, 'FulfillmentAccepted'),
    (BOUNTY_EXPIRED, 'BountyExpired'),
)
