service: puppeteer-screenshots

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1536
  timeout: 180
  iamRoleStatements:
   -  Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource: "arn:aws:s3:::assets.bounties.network/*"  

functions:
  snap-page:
    handler: index.handler
    environment:
      DEBUG: 0

package:
  artifact: ./package.zip
  
plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - npm run package