# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_github_username'),
        ('user', '0004_auto_20180711_1551'),
    ]

    operations = [
    ]
