# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20180712_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dribble',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
