# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180716_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(null=True, to='user.Language'),
        ),
    ]
