# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180803_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isProfileImageDirty',
            field=models.BooleanField(default=False),
        ),
    ]
