# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_isprofileimagedirty'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(max_length=128)),
                ('total_count', models.IntegerField()),
                ('platform', models.CharField(default='main', max_length=128)),
            ],
            options={
                'db_table': 'skill_ranks',
                'managed': False,
            },
        ),
    ]
