# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rankedskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isProfileImageDirty',
            new_name='is_profile_image_dirty',
        ),
    ]
