# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 14:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20180816_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='emails',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'activity': False, 'both': {'RatingIssued': True}, 'fulfiller': {'FulfillmentAcceptedFulfiller': True}, 'issuer': {'BountyCommentReceived': True, 'BountyExpired': True, 'FulfillmentSubmittedIssuer': True, 'FulfillmentUpdatedIssuer': True, 'TransferRecipient': True}}),
        ),
    ]
