# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20180818_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_username',
        ),
    ]
