# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-23 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20180903_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page_preview',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
