# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20180903_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_marketing_emails',
            field=models.BooleanField(default=False),
        ),
    ]
