# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-10 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_wants_marketing_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='large_profile_image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_profile_image_dirty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profileDirectoryHash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profileFileHash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profileFileName',
        ),
        migrations.AddField(
            model_name='user',
            name='small_profile_image_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
