# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20180928_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_marketing_emails',
            field=models.BooleanField(default=False),
        ),
    ]
