# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20181011_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name='user',
            name='last_logged_in',
            field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, blank=True)
        ),
        migrations.AddField(
            model_name='user',
            name='edited',
            field=models.DateTimeField(auto_now=True)
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ens_domain',
            field=models.TextField(max_length=500, blank=True)
        )
    ]
