# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20181011_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
    ]
