# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_created_20181013_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
