# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_dismissed_signup_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dismissed_banner_count',
            field=models.IntegerField(default=0),
        ),
    ]
