# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-09 20:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20190617_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='emails',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'activity': False, 'both': {'FulfillmentCommentReceivedCommenter': True, 'RatingReceived': True}, 'fulfiller': {'ApplicationAcceptedApplicant': True, 'ApplicationRejectedApplicant': True, 'BountyChanged': True, 'BountyChangedApplicant': True, 'BountyCommentReceived': True, 'BountyCommentReceivedCommenter': True, 'FulfillmentAcceptedFulfiller': True, 'FulfillmentCommentReceived': True}, 'issuer': {'ApplicationReceived': True, 'BountyCommentReceivedIssuer': True, 'BountyCompleted': True, 'BountyExpired': True, 'ContributionReceived': True, 'FulfillmentCommentReceivedIssuer': True, 'FulfillmentSubmittedIssuer': True, 'FulfillmentUpdatedIssuer': True, 'TransferRecipient': True}}),
        ),
    ]
