apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-set-bootstrap-conf
data:
  configure-ipfs.sh: |
    #!/bin/sh
    set -e
    set -x
    user=ipfs
    mkdir -p /data/ipfs && chown -R ipfs /data/ipfs

    ipfs init
    ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
    ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
    ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
