apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bounties-subscriber
  namespace: fora-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: bounties-subscriber
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: bounties-subscriber
    spec:
      containers:
      - args:
        - bash
        - -c
        - 'python3 manage.py migrate && python3 manage.py bounties_subscriber'
        env:
        - name: redis_host
          valueFrom:
            secretKeyRef:
              key: host
              name: redis
        - name: redis_port
          valueFrom:
            secretKeyRef:
              key: port
              name: redis
        - name: psql_host
          valueFrom:
            secretKeyRef:
              key: host
              name: psql
        - name: psql_password
          valueFrom:
            secretKeyRef:
              key: password
              name: psql
        - name: psql_port
          valueFrom:
            secretKeyRef:
              key: port
              name: psql
        - name: psql_user
          valueFrom:
            secretKeyRef:
              key: user
              name: psql
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-credentials
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-credentials
        - name: django_secret
          valueFrom:
            secretKeyRef:
              key: secret
              name: django 
        - name: rollbar_token
          valueFrom:
            secretKeyRef:
              key: token
              name: rollbar
        - name: queue_url
          valueFrom:
            secretKeyRef:
              key: host
              name: sqs
        - name: eth_network
          valueFrom:
            secretKeyRef:
              key: network
              name: eth
        - name: slack_token
          valueFrom:
            secretKeyRef:
              key: token
              name: slack
        - name: environment
          valueFrom:
            secretKeyRef:
              key: name
              name: environment
        - name: deploy_url
          valueFrom:
            secretKeyRef:
              key: deploy-url
              name: django
        image: consensysbounties/fora-api:60367ae
        imagePullPolicy: Always
        name: bounties-subscriber
        ports:
        - containerPort: 8888
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
