apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fora-api
  namespace: fora-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: fora-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: fora-api
    spec:
      containers:
      - args:
        - bash
        - -c
        - 'python3 manage.py migrate && uwsgi --http :83 --module bounties.wsgi --processes
          4 --http-keepalive --http-auto-chunked --log-format ''[pid: %(pid)|app:
          -|req: -/-] %(var.HTTP_X_FORWARDED_FOR) (%(user)) {%(vars) vars in %(pktsize)
          bytes} [%(ctime)] %(method) %(uri) => generated %(rsize) bytes in %(msecs)
          msecs (%(proto) %(status)) %(headers) headers in %(hsize) bytes (%(switches)
          switches on core %(core)) referrer: %(referer) UA %(uagent) has wallet:
          %(var.HTTP_HASWALLET) cookies: %(var.HTTP_COOKIE)'''
        env:
        - name: redis_host
          valueFrom:
            secretKeyRef:
              key: host
              name: redis
        - name: redis_port
          valueFrom:
            secretKeyRef:
              key: port
              name: redis
        - name: psql_host
          valueFrom:
            secretKeyRef:
              key: host
              name: psql
        - name: psql_password
          valueFrom:
            secretKeyRef:
              key: password
              name: psql
        - name: psql_port
          valueFrom:
            secretKeyRef:
              key: port
              name: psql
        - name: psql_user
          valueFrom:
            secretKeyRef:
              key: user
              name: psql
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-credentials
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-credentials
        - name: django_secret
          valueFrom:
            secretKeyRef:
              key: secret
              name: django 
        - name: rollbar_token
          valueFrom:
            secretKeyRef:
              key: token
              name: rollbar
        - name: queue_url
          valueFrom:
            secretKeyRef:
              key: host
              name: sqs
        - name: eth_network
          valueFrom:
            secretKeyRef:
              key: network
              name: eth
        - name: slack_token
          valueFrom:
            secretKeyRef:
              key: token
              name: slack
        - name: environment
          valueFrom:
            secretKeyRef:
              key: name
              name: environment
        - name: deploy_url
          valueFrom:
            secretKeyRef:
              key: deploy-url
              name: django
        image: consensysbounties/fora-api:60367ae
        imagePullPolicy: Always
        name: fora-api
        ports:
        - containerPort: 83
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
