DRAFT_STAGE = 0
ACTIVE_STAGE = 1
DEAD_STAGE = 2
COMPLETED_STAGE = 3
EXPIRED_STAGE = 4

STAGE_CHOICES = (
    (DRAFT_STAGE, 'Draft'),
    (ACTIVE_STAGE, 'Active'),
    (DEAD_STAGE, 'Dead'),
    (COMPLETED_STAGE, 'Completed'),
    (EXPIRED_STAGE, 'Expired'),
)

BEGINNER = 0
INTERMEDIATE = 1
ADVANCED = 2

DIFFICULTY_CHOICES = (
    (BEGINNER, 'Beginner'),
    (INTERMEDIATE, 'Intermediate'),
    (ADVANCED, 'Advanced'),
)

ETH = 0
ERC_20 = 20
ERC_721 = 721

TOKEN_CHOICES = (
    (ETH, 'Ether'),
    (ERC_20, 'ERC-20'),
    (ERC_721, 'ERC-721'),
)

STANDARD_BOUNTIES_V1 = '1'
STANDARD_BOUNTIES_V2 = '2'
STANDARD_BOUNTIES_V2_1 = '2.1'
STANDARD_BOUNTIES_V2_2 = '2.2'

CONTRACT_VERSION_CHOICES = (
    (STANDARD_BOUNTIES_V1, 'v1'),
    (STANDARD_BOUNTIES_V2, 'v2'),
    (STANDARD_BOUNTIES_V2_1, 'v2.1'),
    (STANDARD_BOUNTIES_V2_2, 'v2.2'),
)

rev_mapped_difficulties = dict((y, x) for x, y in DIFFICULTY_CHOICES)
