service: ssl-services

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1536
  timeout: 180
  iamRoleStatements:
   -  Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource: "arn:aws:s3:::*"
  environment:
    PRERENDER_TOKEN: ${s3:bounty-secrets/PRERENDER_TOKEN}

functions:
  uploadSitemap:
    handler: handler.uploadSitemap
  setCache:
    handler: handler.setCache
