- args:
    permission:
      allow_aggregations: false
      columns:
      - id
      - emails
      filter:
        user_users:
          id:
            _eq: X-Hasura-User-Id
      limit: null
    role: user
    table:
      name: user_settings
      schema: public
  type: create_select_permission
